[package]
name = "instruction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../../utils" }
sysyc_derive = { path = "../../sysyc_derive" }

llvm = { path = "../../utils/llvm" }
