[package]
name = "sysyc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "sysyc_derive",
  "utils",
  "utils/llvm",
  "frontend/ast",
  "frontend/attr",
  "frontend/symbol",
  "frontend/namer",
  "frontend/scope",
  "frontend/value",
  "frontend/parser",
  "frontend/irgen",
  "backend/basicblock",
  "backend/cfg",
  "backend/func",
  "backend/instruction",
  "backend/program",
]

[dependencies]
utils = { path = "utils" }
llvm = { path = "utils/llvm" }

ast = { path = "frontend/ast" }
parser = { path = "frontend/parser" }
namer = { path = "frontend/namer" }

rrvm_func = { path = "backend/func" }
rrvm_program = { path = "backend/program" }
instruction = { path = "backend/instruction" }

clap = { version = "4.4.7", features = ["derive"] }
anyhow = "1.0.75"
