[package]
name = "sysyc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "sysyc_derive",
  "utils",
  "utils/llvm",
  "frontend/ast",
  "frontend/scope",
  "frontend/ir_gen",
  "frontend/scope",
  "frontend/ir_type",
  "frontend/parser",
]

[dependencies]
utils = { path = "utils" }
ast = { path = "frontend/ast" }
parser = { path = "frontend/parser" }
namer = { path = "frontend/namer" }
ir_gen = { path = "frontend/ir_gen"}

clap = { version = "4.4.7", features = ["derive"] }
anyhow = "1.0.75"
