[package]
name = "ast_optimizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../../utils"}

ast = { path = "../../frontend/ast" }
attr = { path = "../../frontend/attr" }
value = { path = "../../frontend/value" }
