name: build

on: push

jobs:
  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: cargo fmt
      run: cargo fmt --all -- --check
   
  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: cargo clippy
      run: cargo clippy --all --all-targets -- -D warnings
  