
on: push

jobs: 
  test:
    runs-on: ubuntu-latest
    name: Run tests
    container:
      image: coltyangyl/thucst-compiler-21:test0
    steps:
      - name: remove old test
        run: |
          if [ -d 'minidecaf-tests' ]; then rm -r minidecaf-tests; fi
          git clone https://github.com/decaf-lang/minidecaf-tests
          cd ./minidecaf-tests && PROJ_PATH=.. USE_PARALLEL=false ./check.sh
