name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: get test repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TEST_TOKEN }}
        submodules: 'recursive'

    - name: Build compiler
      run: cargo build --workspace --release

    - name: Install RISC-V GNU Compiler Toolchain
      run: |
        echo "PATH=/usr/local/riscv64-toolchain/bin:$PATH" >> $GITHUB_ENV

    - name: build sysylib
      working-directory: ./project-eval/runtime
      run: make

    - name: Run functional test
      working-directory: ./project-eval
      run: python3 test.py -t ./testcases/functional -b

    - name: Run performance test
      working-directory: ./project-eval
      run: python3 test.py -t ./testcases/performance -b
