name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: get test repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TEST_TOKEN }}
        submodules: 'recursive'

    - name: send test request
      working-directory: ./sysyc_tester_client
      run: cargo run -- -a ${{ secrets.BACKEND_ADDRESS }} -p 12345 -b ${{ github.ref_name }} -c ${{ github.sha }}
